services:
  - type: web
    name: amazon-sales-predictor
    env: python
    runtime: python3.11
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python pretrain.py
    startCommand: python run_prod.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RENDER
        value: "true"
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
